# ☁️ Terraform Azure Web Server Lab

This is a Terraform project I built to learn the ropes of Infrastructure as Code and Azure networking. The goal was to deploy a functional Linux VM, handle the networking glue, and auto-install Nginx so the server is live immediately after the command finishes.

## 🏗️ Architecture Overview

The traffic flows from the Internet through a Public IP and is filtered by a Network Security Group (NSG) before reaching the VM.

* 
**Public IP:** Static entry point for the web server.


* 
**Security:** NSG allows SSH (22) and HTTP (80).


* 
**Networking:** A Virtual Network (VNet) with a 10.0.0.0/16 address space and a dedicated 10.0.1.0/24 subnet.


* 
**Compute:** Ubuntu 22.04 LTS running on a `Standard_B1s` instance.


* 
**Automation:** Uses `custom_data` to bootstrap the Nginx installation.



## 📂 Project Structure

* 
**main.tf**: Defines the core resources (VNet, VM, NSG).


* 
**variables.tf**: Holds the project name, resource group, and region defaults.


* 
**outputs.tf**: Displays the Public IP and generates the sensitive SSH private key.



---

## 🚀 Deployment Steps

### 1. Requirements

* Terraform installed locally.


* Azure CLI installed and authenticated via `az login`.


* An active Azure subscription.



### 2. Commands

Run these in your terminal from the project folder:

```bash
# Initialize the providers
terraform init

# Review the changes
terraform plan

# Deploy the infrastructure
terraform apply -auto-approve

```

### 3. Connect to the Server

Since the SSH key is generated by Terraform and marked as sensitive, you need to extract it manually:

```bash
# Export the key to a file
terraform output -raw ssh_private_key > lab_key.pem

# Secure the file permissions
chmod 400 lab_key.pem

# SSH into your new VM
ssh -i lab_key.pem azureuser@<YOUR_PUBLIC_IP>

```

---

## ⚠️ Notes & "Gotchas"

* 
**SSH Security:** Currently, port 22 is open to the entire internet (`*`). In a real production setup, I would restrict `source_address_prefix` to my own IP address.


* 
**Private Key:** The `ssh_private_key` is stored in the `terraform.tfstate` file. Treat that file with care, as it contains the credentials to access your VM.


* **Region:** Defaulted to `eastus`. If you run into "SkuNotAvailable" errors, you can swap this in `variables.tf` to another region like `westeurope`.

